In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/922226-202106/product20210609_tempo002.csv
/kaggle/input/922226/922226_product.csv

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from datetime import datetime

import seaborn as sns
sns.set()

# df = pd.read_csv('../data/train_1.csv')
# df.head()

In [4]:
#Importing dataset
df = pd.read_csv('../input/922226-202106/product20210609_tempo002.csv',dtype={'pid':str,'date':str,'count':int})#.fillna(0)

df.head()

   Unnamed: 0  tempo_id            pid      date  count
0           0         2  0021000615506  20180610      1
1           1         2  0021000615506  20180611      1
2           2         2  0021000615506  20180613      1
3           3         2  0021000615506  20180619      1
4           4         2  0021000615506  20180620      1

In [5]:
df[df["date"]=="20210608"]

        Unnamed: 0  tempo_id            pid      date  count
507            507         2  0021000615506  20210608      2
1510          1510         2       45091520  20210608      5
2502          2502         2       45104916  20210608      5
3572          3572         2       45158254  20210608      1
4457          4457         2       45184888  20210608      2
...            ...       ...            ...       ...    ...
535727      535727         2       49839388  20210608      3
537150      537150         2       49839517  20210608      1
537776      537776         2       49839579  20210608      3
538899      538899         2       49839807  20210608      1
540718      540718         2       49892604  20210608      2

[551 rows x 5 columns]

In [6]:
df2 = df.groupby(by=["pid","date"],as_index=False).sum()

In [7]:
pidlist = list(df2["pid"])

In [8]:
pidlist = df.groupby(by=["pid"],as_index=False).count()["pid"].tolist()

In [9]:
len(pidlist)

1352

In [10]:
df2[df2["pid"] == "0021000615506"]

               pid      date  Unnamed: 0  tempo_id  count
0    0021000615506  20180610           0         2      1
1    0021000615506  20180611           1         2      1
2    0021000615506  20180613           2         2      1
3    0021000615506  20180619           3         2      1
4    0021000615506  20180620           4         2      1
..             ...       ...         ...       ...    ...
503  0021000615506  20210604         503         2      2
504  0021000615506  20210605         504         2      2
505  0021000615506  20210606         505         2      2
506  0021000615506  20210607         506         2      1
507  0021000615506  20210608         507         2      2

[508 rows x 5 columns]

In [49]:
maindf = df2.copy()

In [50]:
# df2['date'] =

In [51]:
# date fill up

dataarray = []

prediction_until = "20210608"
prediction_until_date = datetime(2021,6,8).date()
flag_notcont = False
for r in pidlist:

    pid = r

#     if pid == "4962933252849":
#         flag_notcont = True
    
#     if flag_notcont == False:
#         continue


    dd = df2[df2['pid']==pid]

    #if len(dd) <= 30:
    #    continue


    start_train = dd.iloc[0]['date']
    


    print("pid = ",str(pid))

    datelist = pd.date_range(start=dd.iloc[0]['date'], end=prediction_until)

    dd["date"] = pd.to_datetime(dd["date"])

    dd = dd.set_index('date')
    
    
    last_sale_date_interval = 0#prediction_until_date -datetime.date(dd.index[-1])
    
    if last_sale_date_interval < 15:
        print((datetime.date(dd.index[-1])-datetime(2021,6,8).date()).days," last date = ",dd.index[-1])
        print((datetime.date(dd.index[0])-datetime(2018,6,9).date()).days," start date = ",dd.index[0])
    
    break
    
    continue
    
    
    for a in datelist:
        if str(a.date()) in dd.index:
            # dataarray.append({'date': str(a.date()), 'count':int(1) })
            
            dataarray.append({'date': str(a.date()), 'count':int(dd.loc[str(a.date())]['count']) })
                    
        else:
            pass
            dataarray.append({'date': str(a.date()), 'count': 0})

df3 = pd.DataFrame(dataarray)

pid =  0021000615506
0  last date =  2021-06-08 00:00:00
1  start date =  2018-06-10 00:00:00

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Testing starting and ending date

In [52]:
datetest = maindf.groupby(by="pid",as_index=False).first()

In [53]:
(datetime.date(dd.index[-1])-datetime(2021,6,8).date()).days

0

In [54]:
datetestfirst = maindf.groupby(by="pid",as_index=False).first()
datetestlast = maindf.groupby(by="pid",as_index=False).last()

beforestarting2019 = []
beforeending2021 =[]

cnt = 0
for i,r in datetestfirst.iterrows():
#     print(r["date"])
    deltatimedate = (datetime.date(pd.to_datetime(str(r["date"])))-(datetime(2019,6,8).date())).days
    if deltatimedate > 15:
        beforestarting2019.append(r["pid"])
        
for i,r in datetestlast.iterrows():    
    deltatimedate = (datetime(2021,6,8).date()-datetime.date(pd.to_datetime(str(r["date"])))).days
    if deltatimedate > 15 :
        beforeending2021.append(r["pid"])
        
        
print(cnt)
#len(datetest[datetest["date"]=="20180609"] )

0

In [55]:
len(beforeending2021)

361

In [56]:
maindf = maindf[~maindf["pid"].isin(beforeending2021)]

In [57]:
maindf = maindf[~maindf["pid"].isin(beforestarting2019)]

In [59]:
newpidlist = maindf.groupby(by="pid",as_index=False).count()["pid"]

In [17]:
dataset_start_date = "20190608"
dataset_start_end = "20210608"

datetime.date(2021, 1, 1)

In [18]:
datetest["date"]

0       20210608
1       20210606
2       20190425
3       20190411
4       20190423
          ...
1347    20210314
1348    20210606
1349    20210607
1350    20210607
1351    20210607
Name: date, Length: 1352, dtype: object

In [19]:
datetime(2021,6,8).date()

datetime.date(2021, 6, 8)

In [20]:
dd.index

DatetimeIndex(['2018-06-10', '2018-06-11', '2018-06-13', '2018-06-19',
               '2018-06-20', '2018-06-21', '2018-06-23', '2018-06-27',
               '2018-06-28', '2018-06-30',
               ...
               '2021-05-30', '2021-05-31', '2021-06-01', '2021-06-02',
               '2021-06-03', '2021-06-04', '2021-06-05', '2021-06-06',
               '2021-06-07', '2021-06-08'],
              dtype='datetime64[ns]', name='date', length=508, freq=None)